export const LousaPalette = {
  ink: '#211A24',
  inkSoft: '#716771',
  plum: '#5B365F',
  berry: '#A64D72',
  rose: '#D985A5',
  blush: '#F4DDE6',
  blushSoft: '#FBF4F7',
  pearl: '#FFFDFE',
  lavender: '#B8A6D9',
  moon: '#D8D7E2',
  night: '#17131D',
  nightSoft: '#211B29',
  success: '#4F7563',
  successSoft: '#E7F3ED',
  warning: '#A36F3D',
  warningSoft: '#F8EFE2',
  danger: '#B24C5C',
  dangerSoft: '#FBE8EC',
  line: '#E8DFE4',
  lineDark: 'rgba(255, 255, 255, 0.11)',
} as const;

export const LousaLayout = {
  spacingXs: 4,
  spacingSm: 8,
  spacingMd: 12,
  spacingLg: 16,
  spacingXl: 20,
  spacing2xl: 24,
  spacing3xl: 32,
  spacing4xl: 40,
  spacing5xl: 48,
  screenPaddingCompact: 16,
  screenPadding: 20,
  screenPaddingWide: 24,
  screenVerticalPadding: 16,
  sectionGap: 24,
  cardGap: 12,
  fieldGap: 16,
  labelGap: 8,
  cardRadius: 20,
  heroRadius: 24,
  smallRadius: 16,
  buttonRadius: 18,
  buttonHeight: 56,
  inputHeight: 54,
  touchTarget: 48,
  headerHeight: 60,
  contentMaxWidth: 620,
  bottomContentPadding: 32,
  tabBarHeightAndroid: 62,
  tabBarHeightIos: 72,
  tabBarBottomGap: 7,
  tabContentGap: 28,
} as const;

export const LousaTypography = {
  display: { fontFamily: 'sans-serif-medium', fontSize: 30, lineHeight: 36 },
  screenTitle: { fontFamily: 'sans-serif-medium', fontSize: 26, lineHeight: 32 },
  sectionTitle: { fontFamily: 'sans-serif-medium', fontSize: 20, lineHeight: 26 },
  cardTitle: { fontFamily: 'sans-serif-medium', fontSize: 17, lineHeight: 23 },
  body: { fontFamily: 'sans-serif', fontSize: 16, lineHeight: 24 },
  secondary: { fontFamily: 'sans-serif', fontSize: 14, lineHeight: 20 },
  caption: { fontFamily: 'sans-serif', fontSize: 12, lineHeight: 16 },
  button: { fontFamily: 'sans-serif-medium', fontSize: 15, lineHeight: 20 },
} as const;

export const LousaShadow = {
  soft: {
    shadowColor: '#2C1A31',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.02,
    shadowRadius: 14,
    elevation: 1,
  },
  floating: {
    shadowColor: '#2C1A31',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.05,
    shadowRadius: 18,
    elevation: 3,
  },
} as const;
